### ISSUE TITLE
ToDo for class Wednesday

### ISSUE THREAD

**Issue by Jeff-Ashear** [Player-2-Project-2/Project-2#6]
- [ ] Get the OpenFood API workikng.
- [ ] Get the Kraft Recipe API Working.
- [ ] Come up with cool team name.
- [ ] Pages for each link in the nav.

**Comment by justin1732** [comment]
The APIs were buggy and not working. Changed them to Nutritionix API and the Puppy Recipe API. No NPMs, so we had to queryURL via require and axios.
